/*
 * frmaddressbook.java
 *
 * Created on March 15, 2008, 10:21 PM
 */

package distributedkey;
import java.util.*;
import javax.swing.JOptionPane;
import java.io.*;
import javax.swing.JComboBox;
/**
 *
 * @author  Ganesh Karthick.R
 */
public class frmaddressbook extends javax.swing.JFrame {
    member me;
    Vector vonmbrs;
    Vector<String> vcon;
    groups grps;
    persistentdata pd;
    send s;
    JComboBox jcmboff;
    nodecache nc;
    /** Creates new form frmaddressbook */
    public frmaddressbook() {
        initComponents();
    }
     public frmaddressbook(member me,persistentdata pd,groups grps,send s,JComboBox jcmboff,nodecache nc) {
        initComponents();
        this.me=me;
        this.pd=pd;
        this.grps=grps;
        this.s=s;
        this.nc=nc;
        this.jcmboff=jcmboff;
        vonmbrs=new Vector(5,3);
        vcon=new Vector(5,3);
        Object obj[]=pd.getaddresses();
        if(obj.length!=0)
         for(int i=0;i<obj.length;i++)
            vcon.add((String)obj[i]);
        jlstcontacts.setListData(vcon);
        jlstcontacts.validate();
    }
    public void setonlinembrs(Object obj[])
    {
        jlstonmbrs.setListData(obj);
        for(int i=0;i<obj.length;i++)
           if(!isalreadythere(vonmbrs,(String)obj[i])) 
            vonmbrs.add((String)obj[i]);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlstonmbrs = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlstcontacts = new javax.swing.JList();
        jbtnaddall = new javax.swing.JButton();
        jbtnaddselected = new javax.swing.JButton();
        jbtnremoveselected = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnsave = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(distributedkey.DistributedKeyApp.class).getContext().getResourceMap(frmaddressbook.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jlstonmbrs.setName("jlstonmbrs"); // NOI18N
        jScrollPane1.setViewportView(jlstonmbrs);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jlstcontacts.setName("jlstcontacts"); // NOI18N
        jScrollPane2.setViewportView(jlstcontacts);

        jbtnaddall.setText(resourceMap.getString("jbtnaddall.text")); // NOI18N
        jbtnaddall.setName("jbtnaddall"); // NOI18N
        jbtnaddall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddallActionPerformed(evt);
            }
        });

        jbtnaddselected.setText(resourceMap.getString("jbtnaddselected.text")); // NOI18N
        jbtnaddselected.setName("jbtnaddselected"); // NOI18N
        jbtnaddselected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddselectedActionPerformed(evt);
            }
        });

        jbtnremoveselected.setText(resourceMap.getString("jbtnremoveselected.text")); // NOI18N
        jbtnremoveselected.setName("jbtnremoveselected"); // NOI18N
        jbtnremoveselected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnremoveselectedActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(55, 55, 55)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jbtnremoveselected)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jbtnaddselected, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jbtnaddall, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))))
                    .add(jLabel1))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 27, Short.MAX_VALUE)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(26, 26, 26))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(41, 41, 41)
                        .add(jLabel2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(62, 62, 62))
            .add(jPanel1Layout.createSequentialGroup()
                .add(46, 46, 46)
                .add(jbtnaddall)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtnaddselected)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jbtnremoveselected)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jbtnsave.setText(resourceMap.getString("jbtnsave.text")); // NOI18N
        jbtnsave.setName("jbtnsave"); // NOI18N
        jbtnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsaveActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(208, 208, 208)
                        .add(jbtnsave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jbtnsave, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnaddallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddallActionPerformed
        // TODO add your handling code here:
        Object obj[]=vonmbrs.toArray();
        if(obj.length==0)
        {
            JOptionPane.showMessageDialog(this,"No Items Selected","Distributed Key",0);
            return;
        }
       for(int i=0;i<obj.length;i++)
          if(!isalreadythere(vcon,(String)obj[i]))
            vcon.add((String)obj[i]);
        jlstcontacts.setListData(vcon);
        jlstcontacts.validate();
        pd.setaddrbook(vcon);
        
    }//GEN-LAST:event_jbtnaddallActionPerformed

    private void jbtnaddselectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddselectedActionPerformed
        // TODO add your handling code here:
        Object obj[]=jlstonmbrs.getSelectedValues();
        if(obj.length==0)
        {
            JOptionPane.showMessageDialog(this,"No Items Selected","Distributed Key",0);
            return;
        }
        for(int i=0;i<obj.length;i++)
           if(!isalreadythere(vcon,(String)obj[i])) 
             vcon.add((String)obj[i]);
        jlstcontacts.setListData(vcon);
        jlstcontacts.validate();
    }//GEN-LAST:event_jbtnaddselectedActionPerformed

    private void jbtnremoveselectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnremoveselectedActionPerformed
        // TODO add your handling code here:
        Object obj[]=jlstcontacts.getSelectedValues();
        Object ocon[]=vcon.toArray();
        String id1,id2;
        if(obj.length==0)
        {
            JOptionPane.showMessageDialog(this,"No Items Selected","Distributed Key",0);
            return;
        }
        for(int i=0;i<obj.length;i++)
        {
            id1=(String)obj[i];
            for(int j=0;j<ocon.length;j++)
            {
                id2=(String)obj[j];
                if(id1.equalsIgnoreCase(id2))
                    vcon.removeElementAt(j);
            }
        }
        jlstcontacts.setListData(vcon);
        jlstcontacts.validate();
            
    }//GEN-LAST:event_jbtnremoveselectedActionPerformed
   public persistentdata getpd()
    {
        return pd;
    }
   public void setcontacts(Object obj[])
   {
       for(int i=0;i<obj.length;i++)
          if(!isalreadythere(vcon,(String)obj[i]))
            vcon.add((String)obj[i]);
        jlstcontacts.setListData(vcon);
        jlstcontacts.validate();
   }
   public boolean isalreadythere(Vector v,String id)
   {
        boolean isthere=false;
        Object otmp[]=v.toArray();
        String tmp;
        for(int i=0;i<otmp.length;i++)
        {
            tmp=(String)otmp[i];
            if(id.equalsIgnoreCase(tmp))
                isthere=true;
        }
        return isthere;
   }
    private void jbtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsaveActionPerformed
        // TODO add your handling code here:
        try{
         FileOutputStream foutdat=new FileOutputStream("C:\\"+me.getfname()+".dat");
         ObjectOutputStream oos=new ObjectOutputStream(foutdat);
         Object ombrs[],ogrps[]=grps.getallgroups();
         group gtmp;
         member mtmp;
         pd.createnewgroup();
         pd.setofflinemsgs(s.getofflinemsgs());
         for(int i=0;i<ogrps.length;i++)
          {
             gtmp=(group)ogrps[i];
             ombrs=gtmp.getallmembers();    
             pd.addgroup(gtmp.getid(),gtmp.getowner().getid(),gtmp.getkey(),ombrs); 
         }
         jcmboff.removeAllItems();
         for(int i=0;i<vcon.size();i++)
         {
            pd.addtoaddrbook(((String)vcon.elementAt(i)));   
            jcmboff.addItem(((String)vcon.elementAt(i)));
         }
          pd.setnodecache(nc);
          oos.writeObject(pd);
          oos.flush();
          oos.close();
          JOptionPane.showMessageDialog(this,"Contacts Saved...!!!","Distributed Key",1);   
        }
        catch(Exception ex)
        {
             ex.printStackTrace(); 
        }        
        
    }//GEN-LAST:event_jbtnsaveActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmaddressbook().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnaddall;
    private javax.swing.JButton jbtnaddselected;
    private javax.swing.JButton jbtnremoveselected;
    private javax.swing.JButton jbtnsave;
    private javax.swing.JList jlstcontacts;
    private javax.swing.JList jlstonmbrs;
    // End of variables declaration//GEN-END:variables
    
}
