/*
 * frmlogin.java
 *
 * Created on December 30, 2007, 1:55 PM
 */

package distributedkey;
import java.awt.event.KeyEvent;
import java.util.*;
import java.net.*;
import java.io.*;
import javax.swing.*;
/**
 *
 * @author  Ganesh Karthick.R
 */
public class frmlogin extends javax.swing.JFrame {
    DistributedKeyView dsview;
    DistributedKeyApp dsapp;
    InetAddress iphost;
    String id;
    member me;
    /** Creates new form frmlogin */
    public frmlogin(DistributedKeyApp dsapp) {
        this.dsapp=dsapp;
        initComponents();
        try
        {
         iphost=InetAddress.getLocalHost();
         jtxthost.setText(iphost.getHostName());
         jtxtipaddr.setText(iphost.getHostAddress());
         jtxtport.setText("3000");  
        }
        catch(Exception e)
        {
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
    }
     public frmlogin() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnok = new javax.swing.JButton();
        jbtncancel = new javax.swing.JButton();
        jtxtname = new javax.swing.JTextField();
        jtxthost = new javax.swing.JTextField();
        jtxtport = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtipaddr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtpwd = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(distributedkey.DistributedKeyApp.class).getContext().getResourceMap(frmlogin.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jbtnok.setText(resourceMap.getString("jbtnok.text")); // NOI18N
        jbtnok.setName("jbtnok"); // NOI18N
        jbtnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnokActionPerformed(evt);
            }
        });

        jbtncancel.setText(resourceMap.getString("jbtncancel.text")); // NOI18N
        jbtncancel.setName("jbtncancel"); // NOI18N
        jbtncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncancelActionPerformed(evt);
            }
        });

        jtxtname.setText(resourceMap.getString("jtxtname.text")); // NOI18N
        jtxtname.setName("jtxtname"); // NOI18N

        jtxthost.setText(resourceMap.getString("jtxthost.text")); // NOI18N
        jtxthost.setName("jtxthost"); // NOI18N

        jtxtport.setText(resourceMap.getString("jtxtport.text")); // NOI18N
        jtxtport.setName("jtxtport"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jtxtipaddr.setText(resourceMap.getString("jtxtipaddr.text")); // NOI18N
        jtxtipaddr.setName("jtxtipaddr"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jtxtpwd.setText(resourceMap.getString("jtxtpwd.text")); // NOI18N
        jtxtpwd.setName("jtxtpwd"); // NOI18N
        jtxtpwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpwdKeyReleased(evt);
            }
        });

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jbtnok))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(48, 48, 48)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel4)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(70, 70, 70)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jtxtname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .add(jtxthost, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .add(jtxtpwd, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .add(jtxtipaddr, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .add(jtxtport, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .add(59, 59, 59))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtncancel)
                        .add(93, 93, 93))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jtxtname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtxthost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(14, 14, 14)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jtxtipaddr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(8, 8, 8)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtxtport, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtxtpwd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .add(32, 32, 32)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnok)
                    .add(jbtncancel))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnokActionPerformed
        // TODO add your handling code here:
       int prkey,pukey,port;
      try{ 
       if(jtxtname.getText().equals("")||jtxtname.getText().equals(" "))
       {
           JOptionPane.showMessageDialog(this,"Please Enter Name..!!","Distributed Key",2);
           return;
       }
       if(jtxtpwd.getPassword().length==0)
       {
           JOptionPane.showMessageDialog(this,"Please Enter Password..!!","Distributed Key",2);
           return;
       }
       modfunction mf=new modfunction();
       prkey=gethashvalue(jtxtname.getText(),new String(jtxtpwd.getPassword()))%mf.getprime();
       pukey=mf.getmodval(prkey); //public key calculation
       DatagramSocket ds= new DatagramSocket(Integer.valueOf(jtxtport.getText()));
       ds.close();
       id=jtxtname.getText()+"@"+jtxthost.getText()+"#"+jtxtipaddr.getText()+"#"+jtxtport.getText()+"#"+String.valueOf(pukey); //key
       me=new member(id);
       port=me.getport();
       if(port>=3000&&port<=3010)
       {
        me.setprikey(prkey);
        me.setpassword(new String(jtxtpwd.getPassword()));
        dsview=new DistributedKeyView(dsapp,me,this);
        dsview.setmember(me); 
        jtxtname.setText("");
        jtxtpwd.setText("");
        this.setVisible(false);  
        dsapp.show(dsview);
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Port value exceeded,Please Enter Port between 3000 amd 3010..!!!","Distributed Key",2);
           return;
       }
      }
      catch(Exception ex)
      {
          JOptionPane.showMessageDialog(this,ex.getMessage(),"Distributed Key",2);
      }
     
    }//GEN-LAST:event_jbtnokActionPerformed
   int gethashvalue(String name,String pwd)
   {
            int temp=0;
            String tmp=name+pwd;
            for(int i=0;i<tmp.length();i++)
                temp=temp+(int)tmp.charAt(i);
            return Math.abs(temp);
  }
    private void jbtncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtncancelActionPerformed

    private void jtxtpwdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpwdKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            jbtnokActionPerformed(null);
    }//GEN-LAST:event_jtxtpwdKeyReleased
    public void setApp(DistributedKeyApp dsapp)
    {
      this.dsapp=dsapp;  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmlogin().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtncancel;
    private javax.swing.JButton jbtnok;
    private javax.swing.JTextField jtxthost;
    private javax.swing.JTextField jtxtipaddr;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtport;
    private javax.swing.JPasswordField jtxtpwd;
    // End of variables declaration//GEN-END:variables
    
}
