/*
 * GroupMgmt.java
 *
 * Created on December 30, 2007, 9:09 PM
 */

package distributedkey;
import java.net.*;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author  Ganesh Karthick.R
 */
public class GroupMgmt extends javax.swing.JFrame {
    DatagramSocket ds;
    send s;
    receive r;
    Vector vlstmbr;
    groups grps;
    String cmd;
    member me;
    JList jlstmd,jlstonmbrs;
    JComboBox jcmbgd;
    boolean isstandalone;
    nodecache nc;
    /** Creates new form GroupMgmt */
    public GroupMgmt() {
        initComponents();      
    }
     public GroupMgmt(DatagramSocket ds,send s,receive r,groups grps,JComboBox jcmbgd,JList jlstd,JList jlstonmbrs,member me,boolean isstandalone,nodecache nc) {
        initComponents();
        this.ds=ds;
        this.jlstmd=jlstd;
        this.s=s;
        this.r=r;
        this.grps=grps;
        this.me=me;
        this.jcmbgd=jcmbgd;
        this.jlstonmbrs=jlstonmbrs;
        this.isstandalone=isstandalone;
        this.nc=nc;
        this.setTitle("Group Management:"+me.getname());
        Object ogrps[]=grps.getallgroups();
        if(ogrps!=null)
        {
            group gtmp;
            for(int i=0;i<ogrps.length;i++)
            {
             gtmp=(group)ogrps[i];   
             jcmbgroups.addItem(gtmp.getid());
            }
        }
        vlstmbr=new Vector(5,3);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtgrpname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtncreate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlstmember = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnjoin = new javax.swing.JButton();
        jbtnleave = new javax.swing.JButton();
        jcmbgroups = new javax.swing.JComboBox();
        jbtnrefresh = new javax.swing.JButton();
        jbtndelgrp = new javax.swing.JButton();
        jtxtowner = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(2);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(distributedkey.DistributedKeyApp.class).getContext().getResourceMap(GroupMgmt.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jtxtgrpname.setText(resourceMap.getString("jtxtgrpname.text")); // NOI18N
        jtxtgrpname.setName("jtxtgrpname"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jbtncreate.setText(resourceMap.getString("jbtncreate.text")); // NOI18N
        jbtncreate.setName("jbtncreate"); // NOI18N
        jbtncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncreateActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(80, 80, 80)
                .add(jbtncreate)
                .addContainerGap(89, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 33, Short.MAX_VALUE)
                .add(jtxtgrpname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jtxtgrpname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 184, Short.MAX_VALUE)
                .add(jbtncreate)
                .add(71, 71, 71))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jlstmember.setName("jlstmember"); // NOI18N
        jScrollPane2.setViewportView(jlstmember);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jbtnjoin.setText(resourceMap.getString("jbtnjoin.text")); // NOI18N
        jbtnjoin.setName("jbtnjoin"); // NOI18N
        jbtnjoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnjoinActionPerformed(evt);
            }
        });

        jbtnleave.setText(resourceMap.getString("jbtnleave.text")); // NOI18N
        jbtnleave.setName("jbtnleave"); // NOI18N
        jbtnleave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnleaveActionPerformed(evt);
            }
        });

        jcmbgroups.setSelectedItem("");
        jcmbgroups.setName("jcmbgroups"); // NOI18N
        jcmbgroups.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbgroupsItemStateChanged(evt);
            }
        });
        jcmbgroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbgroupsActionPerformed(evt);
            }
        });

        jbtnrefresh.setText(resourceMap.getString("jbtnrefresh.text")); // NOI18N
        jbtnrefresh.setName("jbtnrefresh"); // NOI18N
        jbtnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrefreshActionPerformed(evt);
            }
        });

        jbtndelgrp.setText(resourceMap.getString("jbtndelgrp.text")); // NOI18N
        jbtndelgrp.setName("jbtndelgrp"); // NOI18N
        jbtndelgrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndelgrpActionPerformed(evt);
            }
        });

        jtxtowner.setBackground(resourceMap.getColor("jtxtowner.background")); // NOI18N
        jtxtowner.setEditable(false);
        jtxtowner.setText(resourceMap.getString("jtxtowner.text")); // NOI18N
        jtxtowner.setName("jtxtowner"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(55, 55, 55)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jbtnjoin, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jbtnrefresh, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(35, 35, 35)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jbtnleave, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jbtndelgrp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(33, 33, 33))
            .add(jPanel2Layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jcmbgroups, 0, 281, Short.MAX_VALUE)
                    .add(jtxtowner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .add(jLabel3)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .add(jLabel2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jcmbgroups, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtxtowner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                .add(jLabel3)
                .add(18, 18, 18)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnjoin)
                    .add(jbtnleave))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnrefresh)
                    .add(jbtndelgrp))
                .add(19, 19, 19))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbgroupsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbgroupsItemStateChanged
        // TODO add your handling code here:
        try{
         if(jcmbgroups.getSelectedItem()==null)
            return;
        String temp=(String)jcmbgroups.getSelectedItem();
        group g=grps.getgroup(temp);
        jtxtowner.setText(g.getowner().getid());
        jlstmember.removeAll();
        jlstmember.setListData(g.getvector());
        jlstmember.validate();
       // System.out.println(temp+" "+g+" Hi ");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }   
        
    }//GEN-LAST:event_jcmbgroupsItemStateChanged
public boolean isalreadythere(Vector v,String s) 
 {
     Iterator itr=v.iterator();
     String stmp;
     boolean flag=false;
     while(itr.hasNext())
     {
	  stmp=(String)itr.next();
	  if(stmp.equalsIgnoreCase(s))
	  flag = true;
     } 
     return flag;
}
 public Vector getallitems(JComboBox jcmb)
 {
     Vector vtmp=new Vector(jcmb.getItemCount());
     for(int i=0;i<jcmb.getItemCount();i++)
         vtmp.add(jcmb.getItemAt(i));
     return vtmp;
 }
    private void jbtncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncreateActionPerformed
        // TODO add your handling code here: 
        try{
         if(jtxtgrpname.getText()==null)
         {
              JOptionPane.showMessageDialog(this,"Please enter group name..!!!","Distributed Key",0);
              return; 
         } //CREATE GROUP:groupname:ownerid
         
         String tg,td;
         cmd="CRTEGRP:"+jtxtgrpname.getText()+":"+me.getid();
         group g=new group(jtxtgrpname.getText(),me,s,nc,me);
         if(isalreadythere(getallitems(jcmbgroups),g.getid()))
         {
             JOptionPane.showMessageDialog(this,"Group already exists,Please enter another group name..!!!","Distributed Key",0);
             return;
         }    
         g.addmember(me.getid());
         g.startkeydaemon(me.getid());
         grps.addgroup(g);
         jcmbgroups.addItem(g.getid());// add to group management combo box
         jcmbgd.addItem(g.getid());//add to distributed combo box
         tg=(String)jcmbgroups.getSelectedItem();
         td=(String)jcmbgd.getSelectedItem();
         if(tg.equalsIgnoreCase(g.getid()))
             jlstmember.setListData(g.getvector());
         if(td.equalsIgnoreCase(g.getid()))
             jlstmd.setListData(g.getvector());
        synchronized(s)
        {
         s.sendmsg(cmd,false); 
        }
         JOptionPane.showMessageDialog(this,jtxtgrpname.getText()+" group is created..!!","Distributed Key",1);
         jtxtgrpname.setText("");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }   
    }//GEN-LAST:event_jbtncreateActionPerformed

    private void jbtnjoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnjoinActionPerformed
        // TODO add your handling code here:
        try{
         String tmp=(String)jcmbgroups.getSelectedItem();
         group g;
         synchronized(grps)
         {
          g=grps.getgroup(tmp);
          if(!g.ismember(me.getid()))
          {
            g.addmember(me); //JOIN GROUP
            grps.setgroup(tmp, g);
            grps.startkeydaemonforgroup(g.getid());  
          }
          else
          {
           JOptionPane.showMessageDialog(this,"You are already a member of the group "+tmp+" ..!!","Distributed Key",1);
           return;
          }
         } //JOIN:groupid:your id
        cmd="JOIN:"+g.getid()+":"+me.getid();
        s.sendmsg(cmd,false); 
        JOptionPane.showMessageDialog(this,"You have joined the group "+tmp+" ..!!","Distributed Key",1);       
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
            System.out.println(ex.toString());
        }  
        
    }//GEN-LAST:event_jbtnjoinActionPerformed

    private void jbtnleaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnleaveActionPerformed
        // TODO add your handling code here:
        try{
         String tmp=(String)jcmbgroups.getSelectedItem();
         group g;
         synchronized(grps)
         {
          g=grps.getgroup(tmp);
          if(g.getowner().getid().equalsIgnoreCase(me.getid()))
          {
              JOptionPane.showMessageDialog(this,"You are the owner of the group , you cannot leave the group ..!!","Distributed Key",1);
              return;
          }
          if(g.ismember(me.getid()))
          {
           synchronized(g){
           g.setkey(0);
           g.removemember(me); //LEAVE GROUP
           }
           g.stopkeydaemon();
           grps.setgroup(tmp, g);
          }
          else
          {
           JOptionPane.showMessageDialog(this,"You have already left the group or not a member of the group "+tmp+" ..!!","Distributed Key",1);    
           return;
          }
         } //LEAVE:groupid:your id
         cmd="LEAVE:"+g.getid()+":"+me.getid();
         s.sendmsg(cmd,false); 
         JOptionPane.showMessageDialog(this,"You have left the group "+tmp+" ..!!","Distributed Key",1);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
            
        }  
       
    }//GEN-LAST:event_jbtnleaveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        return;
    }//GEN-LAST:event_formWindowClosing

    private void jbtnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrefreshActionPerformed
        // TODO add your handling code here:
        cmd="REFGRP:"+me.getid();
        s.sendmsg(cmd,false);
    }//GEN-LAST:event_jbtnrefreshActionPerformed

    private void jbtndelgrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndelgrpActionPerformed
        // TODO add your handling code here:
        String tmp,gid = (String)jcmbgroups.getSelectedItem();
        if(gid==null)
            return;
        try{
        group g=grps.getgroup(gid);
        if(g.getowner().getid().equalsIgnoreCase(me.getid()))
        {
            cmd="DELGRP:"+me.getid()+":"+g.getid();
            s.sendmsg(cmd,false);
            JOptionPane.showMessageDialog(this,"You have deleted the group "+gid+" ..!!","Distributed Key",1);
            for(int i=0;i<jcmbgd.getItemCount();i++) 
                 {
                     tmp=(String)jcmbgd.getItemAt(i);
                     if(tmp.equalsIgnoreCase(gid))
                     {
                         jcmbgd.removeItemAt(i);
                         
                     }
                 }
            for(int i=0;i<jcmbgroups.getItemCount();i++) 
                 {
                     tmp=(String)jcmbgroups.getItemAt(i);
                     if(tmp.equalsIgnoreCase(gid))
                     {
                         jcmbgroups.removeItemAt(i);
                         
                     }
                 }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"You are not a owner of this group, So You cannot delete it..!!!","Distributed Key",1);
        }
       }
       catch(Exception ex) 
       {
           ex.printStackTrace();
       }
    }//GEN-LAST:event_jbtndelgrpActionPerformed

    private void jcmbgroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbgroupsActionPerformed
        // TODO add your handling code here:
        try{
         if(jcmbgroups.getSelectedItem()==null)
            return;
        String temp=(String)jcmbgroups.getSelectedItem();
        group g=grps.getgroup(temp);
        jtxtowner.setText(g.getowner().getid());
        jlstmember.removeAll();
        jlstmember.setListData(g.getvector());
        jlstmember.validate();
       // System.out.println(temp+" "+g+" Hi ");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }   
    }//GEN-LAST:event_jcmbgroupsActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupMgmt().setVisible(true);
            }
        });
    }
    public JComboBox getgroupcontainer()
    {
        return jcmbgroups;
    }
    public JList getmembercontainer()
    {
        return jlstmember;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtncreate;
    private javax.swing.JButton jbtndelgrp;
    private javax.swing.JButton jbtnjoin;
    private javax.swing.JButton jbtnleave;
    private javax.swing.JButton jbtnrefresh;
    private javax.swing.JComboBox jcmbgroups;
    private javax.swing.JList jlstmember;
    private javax.swing.JTextField jtxtgrpname;
    private javax.swing.JTextField jtxtowner;
    // End of variables declaration//GEN-END:variables
    
}
